export const GET_BATCH = "GET_BATCH";
export const BATCH_LOADED = "BATCH_LOADED";
export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL";
export const FETCH_LOADED = "FETCH_LOADED";
export const BATCH_DETAIL_LOADED = "BATCH_DETAIL_LOADED";
export const SET_SHIPMENT_ITEMS = "SET_SHIPMENT_ITEMS";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const ALL_ORDERS_LOADED = "ALL_ORDERS_LOADED";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_DATA_LOADED_IN = "AUTH_DATA_LOADED_IN";
export const AUTH_DATA_LOADED_OUT = "AUTH_DATA_LOADED_OUT";
export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_CHECK_LOADED = "AUTH_CHECK_LOADED";
export const GET_TOKEN = "GET_TOKEN";
export const TOKEN_LOADED = "TOKEN_LOADED";

export const GET_SHIPMENT_METRICS = "GET_SHIPMENT_METRICS";
export const SHIPMENT_METRICS_LOADED = "SHIPMENT_METRICS_LOADED";
export const GET_ORDER_METRICS = "GET_ORDER_METRICS";
export const ORDER_METRICS_LOADED = "ORDER_METRICS_LOADED";
export const GET_CUSTOMER_METRICS = "GET_CUSTOMER_METRICS";
export const CUSTOMER_METRICS_LOADED = "CUSTOMER_METRICS_LOADED";

