export const GET_BATCH = "GET_BATCH";
export const BATCH_LOADED = "BATCH_LOADED";
export const GET_BATCH_DETAIL = "GET_BATCH_DETAIL";
export const BATCH_DETAIL_LOADED = "BATCH_DETAIL_LOADED";
export const SET_SHIPMENT_ITEMS = "SET_SHIPMENT_ITEMS";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_DATA_LOADED_IN = "AUTH_DATA_LOADED_IN";
export const AUTH_DATA_LOADED_OUT = "AUTH_DATA_LOADED_OUT";
export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_CHECK_LOADED = "AUTH_CHECK_LOADED";
